### PR TITLE
Sort them all

### PR DESCRIPTION
**Pull request by Nightenom**
Make the JsonObjects sorted, I wanted to extend the JsonObject but it's final and unextendable because of package private abstract method.
Tested on structurize, running the datagen twice produces no git diff

### CODE REVIEW

**Comment by Nightenom** [comment]
@OrionDevelopment not sure if I can bump gradle to 6.8 without screwing up CI

**Comment by Raycoms** [comment]
:shipit:

**Review by marchermans — CHANGES_REQUESTED** [review]
Gradle can't t be updated this way. Leave it at the version the mdk specifies, which should be 4.10?

**Comment by Nightenom** [comment]
Done, mergeable

**Pull request merged**
